//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Padfolio_Dapper_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNote
    {
        public int UserNoteId { get; set; }
        public string UserNoteTitle { get; set; }
        public string UserNoteExplanation { get; set; }
    }
}
